name: Reusable Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
    secrets:
      aws-role-arn:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application
        uses: actions/checkout@v4
      
      - name: Deploy
        working-directory: app-service
        env:
          AWS_ROLE_ARN: ${{ secrets.aws-role-arn }}
        run: make deploy ENV=${{ inputs.environment}}