name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      severity:
        description: "Trivy severity levels to fail on"
        required: false
        type: string
        default: "CRITICAL,HIGH"

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          severity: ${{ inputs.severity }}
          exit-code: "1"
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability and secret scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          scanners: "vuln,secret"
          severity: ${{ inputs.severity }}
          exit-code: "1"